### ISSUE TITLE
Settings cog icon is obscured

### ISSUE THREAD

**Issue by lydenyardley** [leggett/simplify#21]
![Screenshot 2019-04-06 at 07 59 30](https://user-images.githubusercontent.com/2838799/55666128-f3ec9f00-5841-11e9-81c3-f568bd82c061.png)

The settings cog icon is obscured. See screenshot.

- Browser: Chrome latest
- Gmail theme: Default
- OS: MacOS latest

**Comment by leggett** [comment]
Thanks for the report. You have preview pane enabled. If you don't use the preview pane, you can disable it under Settings > Advanced > Preview Pane and that button will go away. 

Not many have any of the advanced features enabled but I do plan to fix this and properly support it this weekend.

**Comment by leggett** [comment]
Fixed in 1.0.7 which I will deploy shortly.

**Comment by lydenyardley** [comment]
Nailed it! Thanks so much

**Comment by shellen** [comment]
Still seeing this even if the preview pane is disabled. Particularly if another plugin is installed. I have the Streak app on for Gmail. ![Stacks_app_-_shellen_gmail_com_-_Gmail](https://user-images.githubusercontent.com/106165/55763243-f6562100-5a1a-11e9-9dbf-290f52a4cbec.png)
