### ISSUE TITLE
addon menu doesn't always include 3rd party add-ons under 'more'

### ISSUE THREAD

**Issue by zanona** [leggett/simplify#238]
The only problem I am facing right now is that for custom or 3rd party add-ons sometimes their icons show up but sometimes they don't?

With Simplify extension on:
<img src=https://user-images.githubusercontent.com/32017/58463718-a8b18700-8134-11e9-9c61-13bae160923a.png height=300>

With Simply extension off, notice the last icon:
<img src=https://user-images.githubusercontent.com/32017/58463743-b535df80-8134-11e9-8970-05af4f5be24e.png height=300>

And this was me using the extension a few minutes after (3rd party add-on now showing again)
<img src=https://user-images.githubusercontent.com/32017/58463849-e6aeab00-8134-11e9-85b1-c3b0bcea3a38.png height=300>

The only way I can work around it at the moment is by disabling the extension, reaching to the add-on menu and then switch it back on.

_Originally posted by @zanona in https://github.com/leggett/simplify/issues/15#issuecomment-496422695_

### Update

For replicating you can try to install the '[Gfycat GIFs](https://gsuite.google.com/marketplace/app/gfycat_gifs_for_gmail/410858369375?hl=en-GB&pann=gaw)' add-on which is publicly available under the add-on marketplace

**Comment by leggett** [comment]
Thanks for such a detailed report. I'll look into it.

**Comment by leggett** [comment]
I think I've fixed this in v1.7.2 which is live in Firefox now and should be live in Chrome in a week or so.

**Comment by zanona** [comment]
Thanks for this @leggett. Unfortunately I am still getting the same issue? It shows up sporadically.
https://github.com/leggett/simplify/commit/fc5e85261403ddb823619e118bcc899d75c3fcd4#diff-695016f5c91c8995d61bc180a2a5fd75L1088-L1089
Perhaps it would be possible to rely on events sent through postMessage, instead of a timeout?

**Comment by leggett** [comment]
Do you have Simplify v1.7.2? It is only live on Firefox right now.

I cache how many there are so it is meant to be something I check well after the page has loaded (the timeout could be even longer) to see if it changed since the last time I checked.

The issue with relying on events is I haven't been able to pin point how I know if 3rd party add-ons have been loaded VS there aren't any and they never will be loaded. I also didn't want to leave a mutation observer active for detecting it as I think the adding or removing of add-ons is a very infrequent action. But maybe I'm missing something.

**Comment by zanona** [comment]
@leggett, Yes. I updated it on Firefox yesterday. 1.7.2
> Added new setting (ability to hide unread count in nav) plus small bug fixes (not all add-ons were being shown and the link to settings wasn't working)

It's a tricky situation, isn't it? I tried to listen to events fired from 'postMessage' but it's indeed difficult to understand which one to pinpoint. I wonder if Gmail also fires custom events we could try to listen to, but I don't know how to check for those, I'm afraid.

From what I could check, if you try to listen to messages that have a format like: ` 9f0fTmDt4F|cse:(number)` we can see that a last one is sent immediately after the add-ons finishes loading. But then, if you click to add an extension and get a pop-up, once closed, it tries to load the extensions again but no messages are sent besides a polling one sending the number 2. Quite curious.
 
```js
addEventListener('message', (m) => m.data.match('cse:') ? console.log(m.data) : void 0)
```

**Comment by leggett** [comment]
@zanona I dug into it some more and found the problem. It is already live on Firefox and should be live on Chrome in a week. It shouldn't break again this time.

**Comment by leggett** [comment]
P.S. I added Gfycat and confirmed it works too now.

**Comment by zanona** [comment]
Thanks, @leggett.
I just upgraded to 1.7.3 but I'm afraid the issue persists.
A bit worse now as if I disable Simplify with the shortcut (Ctrl+S) to then reach to the extensions, it is now removing those? See attached
![image](https://user-images.githubusercontent.com/32017/71084897-919cba00-2196-11ea-9099-758c1d67ed96.png)
whereas with the extension disabled from Firefox add-on panels, it gets back to normal:
![image](https://user-images.githubusercontent.com/32017/71084953-b09b4c00-2196-11ea-9cb6-0c5a87414e46.png)
I only have been able to get the add-ons showing on Simplify a couple of times after testing and reloading quite a lot :)

**Comment by leggett** [comment]
I'm tracking this in #244 now – I pushed another update last night (v1.7.4). Can you let me know if that fixes it for you?

**Comment by zanona** [comment]
Hey @leggett! It works perfectly now!! Very nice!
Thanks so much!
