### ISSUE TITLE
Search chips overlapping search result in a Workspace account, fine in others and personal Gmail

### ISSUE THREAD

**Issue by erikgeurts** [leggett/simplify#768]
I work for multiple organisations and thus in multiple Workspace accounts. I also have a personal Gmail account. I access all of them on the same devices.

In one of the Workspace accounts, when I do a search, the chips at the top of the results are overlapping with the results:
![Screenshot 2023-10-19 14 26 53](https://github.com/leggett/simplify/assets/5102461/8158af8c-4ca8-468e-a922-2461524ad65f)

In the other Workspace accounts and in plain Gmail, it works fine, the chips are above the results:
![Screenshot 2023-10-19 14 31 53](https://github.com/leggett/simplify/assets/5102461/6d71497d-b05a-40f8-87e9-a4b13157bc1a)

Both screenshots were taken from the same Chromebook within minutes of each other, but it happens in Chrome for Windows as well.

---
Simplify v.2.5.43 - Configuration: aAX appMenuOpen appNavOff ca3 caI caL cfC cfO cfQ cfR cfU cfZ composeActions composeFab composeFormat dateGroup defaultTheme fontMsg hideLabelChips hideListCount hideMsgCount hideTabIcons highDensity inList inSearch invertAddons izBgDefault lightTheme listWidthLg matYou minimizeChat msgLabelsRight msgWidthMd newNav newUI sendLater simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (X11 CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 - Window: 1272 x 782 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment]
Thanks Erik. Gmail is in the process of changing some of the DOM around the list and search chips. I've got a fix out in [the v3 beta](https://beta.simpl.fyi) which is really close to going out of beta as an update to everyone.

**Comment by erikgeurts** [comment]
Even though I'm involved in software development myself and understand the importance of beta testing, I'd prefer to use a full release on my production devices. Is there a way to install the Simplify beta on just one device and continue using v2.xyz on my other devices? And once the beta phase is over, is it possible to easily switch back to the full release?

**Comment by leggett** [comment]
- I pushed the fixes to this an other things today for v2. The update is already approved for Firefox and out to 10% of users on Chrome. I'll roll out to everyone by end of tomorrow. Edge will take a couple weeks to approve and Apple is giving me a hard time for not using Apple Pay so no idea when Safari will get updated. Hopefully in the next 24 hours.
- You can install either on any device, your plan will work across them all
- You can switch between them, the only downside is preferences are not shared/synced
- I would say the v3 version is actually more stable now because it is the one I use every day

**Comment by erikgeurts** [comment]
I just updated to 2.5.44, and it did make a small difference but there's still an overlap going on in the same Workspace account that had it before:
![image](https://github.com/leggett/simplify/assets/5102461/b78d0f1b-14d1-452d-ba5b-610395a399d4)

The problem is that it's not possible to click the conversation that happens to be underneath the row of search chips

**Comment by leggett** [comment]
I'm not seeing the issue on v2.5.44. Maybe you need a hard refresh? Or maybe there is another extension or something unique to your account that is causing the issue?

<img width="1125" alt="image" src="https://github.com/leggett/simplify/assets/8763662/816918f7-0e6a-4135-bb7f-9c09d7333455">

**Comment by leggett** [comment]
Ok, I found this broken on a different account and forgot that there were two ways this breaks. v3.0.43+ already has the fix.

Will push another update (v2.5.45) and hopefully that will fix it for good.

**Comment by erikgeurts** [comment]
I got the v2.5.45 release on my Chromebook and also on Chrome for Windows, but unfortunately, this overlap still occurs. What's odd (to me) is that it happens only in 1 of 3 Workspace accounts I use, it's fine in the other 2 and in vanilla Gmail.

**Comment by leggett** [comment]
Well that is frustrating! Two thoughts:

1. I'm guessing there is something unique about that 3rd Workspace account. Maybe it is a delegate account or maybe Gmail is rolling out some other change that has hit that account first (or maybe a recent change hasn't reached that account). Or the Gmail account is just configured slightly differently. It could be so many things sadly but let me know if you have any ideas.

2. Or maybe I've just more thoroughly fixed this in v3. Can you try switching over to [Simplify v3](https://beta.simpl.fyi) to see if it is fixed there on that other account? You'll want to disable Simplify v2 (but don't remove it -- you can disable or remove v3 afterwards and re-enable v2).

**Comment by erikgeurts** [comment]
I tried with the v3 (Canary) and the same thing occurs, the chips partially overlap the first search result.

![image](https://github.com/leggett/simplify/assets/5102461/33fdbc33-713a-4f3e-a26c-890ddfe497ed)

As with the v2, only in this one specific Workspace account. I don't really see anything special about it, it's not a delegate account, and 2 other Workspace accounts I also access on a daily basis do not have this behavior.

**Comment by leggett** [comment]
Something else to try: 
1. Enable Reading Pane under https://mail.google.com/mail/#settings/inbox
2. Set it to No Split
3. Refresh Gmail

**Comment by leggett** [comment]
(or if it was already enabled but not used, try disabling it entirely)

**Comment by leggett** [comment]
And if that doesn't fix it, maybe we can schedule a 5 minute video call so I can troubleshoot further since I can't reproduce the issue? You can email me at hi@simpl.fyi to coordinate.

**Comment by erikgeurts** [comment]
I've had a look at the settings for the Reading pane in the affected Workspace account. For the record: I have never used the Reading pane, I see no need for it, and it was disabled entirely:
![image](https://github.com/leggett/simplify/assets/5102461/1c7bc7e1-7515-4f97-963a-6b03715551a5)

As per your suggestion, I enabled it and set it to No Split, and after refreshing the application, I tried searching for a term. The search results are not overlapped with the chips anymore:
![image](https://github.com/leggett/simplify/assets/5102461/4eeb90bb-be05-4500-b71a-524fe933566d)

In the other Workspace accounts where the overlap issue did not occur, the Reading Pane was (and has always been) disabled.

Your suggested work around fits my needs, except for that reading pane button showing up when I hover over my account headshot. My preference would be to have no mention of reading pane at all, but it's not a big deal to have that button there that's only visible when I hover my photo.

**Comment by leggett** [comment]
100% agree that this shouldn't be needed and is annoying. I'd be happy to do a short video call to see if I can understand why it isn't working in the other account. Email me at hi@simpl.fyi to schedule something if you want to do that.

**Comment by erikgeurts** [comment]
My immediate itch has been scratched, in the affected Workspace account (1 of the 3 I work in on a daily basis). The other 2 never had this (even with the same Reading pane settings).

I'll drop you an email in case you think it's useful to have a quick call. Do keep in mind I'm many time zones away from you.

**Comment by leggett** [comment]
By the way, this has been fixed and you can turn off reading panes now.

**Comment by erikgeurts** [comment]
I got v2.5.45 here, but I'm afraid I still see the overlapping issue of the search chips in the Workspace account we looked at together (after disabling the reading pane). Or is there an even newer version still on the way that I haven't received yet?

**Comment by leggett** [comment]
Ah, no, you're right. I only deployed the fix to v3. I'm getting REALLY close to launching v3 to everyone... maybe even this weekend. So I'm going to hold off on updating v2 for just this bug.

**Comment by erikgeurts** [comment]
I'm glad this fix is upcoming in v3, because this issue is now also starting to occur in my personal Gmail account and one of the other Workspace accounts.
